// Interface automatically generated by schemas-to-ts

import { Tag } from '../../../tag/content-types/tag/tag';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Tag_Plain } from '../../../tag/content-types/tag/tag';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Image {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    description: string;
    tag?: { data: Tag };
    image?: { data: Media };
    locale: string;
    localizations?: { data: Image[] };
  };
}
export interface Image_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description: string;
  tag?: Tag_Plain;
  image?: Media_Plain;
  locale: string;
  localizations?: Image_Plain[];
}

export interface Image_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description: string;
  tag?: number;
  image?: number;
  locale: string;
  localizations?: Image[];
}

export interface Image_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description: string;
  tag?: AdminPanelRelationPropertyModification<Tag_Plain>;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
  locale: string;
  localizations?: Image[];
}
