// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Category {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    coverImage?: { data: Media };
    category?: string;
    locale: string;
    localizations?: { data: Category[] };
  };
}
export interface Category_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  coverImage?: Media_Plain;
  category?: string;
  locale: string;
  localizations?: Category_Plain[];
}

export interface Category_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  coverImage?: number;
  category?: string;
  locale: string;
  localizations?: Category[];
}

export interface Category_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  coverImage?: AdminPanelRelationPropertyModification<Media_Plain>;
  category?: string;
  locale: string;
  localizations?: Category[];
}
