declare global {
// Interface automatically generated by schemas-to-ts

interface MediaFormat {
      name: string;
      hash: string;
      ext: string;
      mime: string;
      width: number;
      height: number;
      size: number;
      path: string;
      url: string;
    }
}

export {};