declare global {
// Interface automatically generated by schemas-to-ts

interface Payload<T> {
      data: T;
      meta: {
        pagination?: {
          page: number;
          pageSize: number;
          pageCount: number;
          total: number;
        }
      };
    }
}

export {};