// Interface automatically generated by schemas-to-ts

import { Tag } from './tag';
import { Media } from '../common/Media';
import { Tag_Plain } from './tag';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Image {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    description?: string;
    tags: { data: Tag[] };
    image?: { data: Media };
    locale: string;
    localizations?: { data: Image[] };
  };
}
export interface Image_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  tags: Tag_Plain[];
  image?: Media_Plain;
  locale: string;
  localizations?: Image_Plain[];
}

export interface Image_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  tags: number[];
  image?: number;
  locale: string;
  localizations?: Image[];
}

export interface Image_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  tags: AdminPanelRelationPropertyModification<Tag_Plain>;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
  locale: string;
  localizations?: Image[];
}
