// Interface automatically generated by schemas-to-ts

export interface InstagramFeed {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    feedId?: string;
    tagName?: string;
  };
}
export interface InstagramFeed_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  feedId?: string;
  tagName?: string;
}

export interface InstagramFeed_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  feedId?: string;
  tagName?: string;
}

export interface InstagramFeed_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  feedId?: string;
  tagName?: string;
}
